# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # Ci
  # desc "Run tests"
  # lane :test do
  #   scan(
  #     scheme: "CatchMate", 
  #     device: "iPhone 15 Pro", 
  #     clean: true
  #   )
  # end

  desc "Deploy to Firebase"
  lane :deploy_firebase do
    match(
      type: "development", # "development", "adhoc", "appstore", or "enterprise"
      readonly: false,
      git_url: ENV['MATCH_GIT_URL'],
      password: ENV['MATCH_PASSWORD']
    )
    # Build the app
    build_app(
      project: "../CatchMate.xcodeproj",
      scheme: "CatchMate",
      configuration: "Debug",
      export_options: {
        provisioningProfiles: {
          "com.tori.CatchMate" => "match Development com.tori.CatchMate"
        },
        allowProvisioningUpdates: true
      }
    )
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: "Dugout-TeckNeck", 
      release_notes: ENV['CHANGELOG']
      firebase_cli_token: ENV['FIREBASE_API_TOKEN']
    )
  end
end
