# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - release/*
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ruby/setup-ruby@v1
        uses: actions/setup-ruby
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Build and test
        run: bundle exec fastlane test

  deploy_firebase:
    if: github.ref == 'refs/heads/develop'
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up environment variables
        run: |
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_API_TOKEN=${{ secrets.FIREBASE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Get Commit Message
        id: get_commit
        run: echo "::set-output name=msg::$(git log -1 --pretty=format:'%s')"

      - name: Deploy to Firebase
        env:
          CHANGELOG: ${{ steps.get_commit.outputs.msg }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_API_TOKEN: ${{ secrets.FIREBASE_API_TOKEN }}
        run: bundle exec fastlane deploy_firebase

